shellEmulator: true
trustPolicy: no-downgrade
patchedDependencies:
  nuxt-studio@1.6.0: patches/nuxt-studio.patch
allowBuilds:
  '@parcel/watcher': true
  core-js-pure: false
  dtrace-provider: false
  esbuild: true
  protobufjs: false
  re2: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
